ci(build): add trigger and check deploy step at backend.yml workflow

diff --git a/.github/workflows/backend.yml b/.github/workflows/backend.yml
--- a/.github/workflows/backend.yml
+++ b/.github/workflows/backend.yml
@@ -1,11 +1,9 @@
 name: Continous Deployment Backend
 
 on:
-  # pull_request:
-  #   types: [closed]
-  #   branches: [main]
-  push:
-    branches: [task/#100]
+  pull_request:
+    types: [closed]
+    branches: [main]
 
 env:
   CHANGES: 'false'
@@ -25,3 +23,39 @@ jobs:
 
       - name: Push Docker image
         run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
+
+      - name: Trigger and Check Deploy Status
+        run: |
+          DEPLOY_ID=$(curl \
+            --request POST \
+            --url https://api.render.com/v1/services/${{secrets.BACKEND_RENDER_SERVICE_ID}}/deploys \
+            --header 'authorization: Bearer ${{secrets.RENDER_API_KEY}}' \
+            --header 'accept: application/json' \
+            --header 'content-type: application/json' \
+            --data '{ "clearCache": "do_not_clear" }' | jq -r '.id')
+          
+          previous_status=""
+          while true; do
+            sleep 10
+            status=$(curl -s \
+              --request GET \
+              --url "https://api.render.com/v1/services/${{ secrets.BACKEND_RENDER_SERVICE_ID }}/deploys/$DEPLOY_ID" \
+              --header "Authorization: Bearer ${{secrets.RENDER_API_KEY}}" \
+              --header "Content-Type: application/json" | jq -r '.status')
+
+            if [[ "$status" != "$previous_status" ]]; then
+              echo "Deploy status: $status"
+              previous_status="$status"
+            fi
+
+            if [[ "$status" == *"failed"* ]] || [[ "$status" == "canceled" ]] || [[ "$status" == "deactivated" ]]; then
+              echo "Deploy status: $status"
+              echo "Deployment failed"
+              exit 1
+            fi
+
+            if [[ "$status" == "live" ]]; then
+              echo "Deploy finished successfully"
+              exit 0
+            fi
+          done
